#!/bin/bash
#                   ______     ___           __ __
#                  / ____/__  / (_)  __     / //_/_  ____  ______
#                 / /_  / _ \/ / / |/_/    / ,< / / / / / / / __ \
#                / __/ /  __/ / />  <     / /| / /_/ / /_/ / / / /
#               /_/    \___/_/_/_/|_|____/_/ |_\__, /\__,_/_/ /_/
#                                  /_____/    /____/
#                               FK Utility

# will add func later
# for now just basic func only 

music() {
    # Music Func 
    # Valid args 
    #   - update 
    #   - ...
    case $1 in 
    
    update)
        ./bin/base-update-music.sh
        ;;
    *)
        echo -e " An Error Occured!!"
        ;;
    esac
}