#!/bin/bash
#                   ______     ___           __ __
#                  / ____/__  / (_)  __     / //_/_  ____  ______
#                 / /_  / _ \/ / / |/_/    / ,< / / / / / / / __ \
#                / __/ /  __/ / />  <     / /| / /_/ / /_/ / / / /
#               /_/    \___/_/_/_/|_|____/_/ |_\__, /\__,_/_/ /_/
#                                  /_____/    /____/
#                               FK Utility

# usage: fk [-subcommand] [-value]
# sub_cmd
#   music
#   dots
#   ...
# music 
#   update
#   add 

music() {
    echo music func running;
}

case $1 in
    music)
        echo music
        ;;
    *)
        echo "
            help message displayed here;
            idk....
        "
        ;;
esac