#! /usr/bin/env bash 

PULL_URL=""

echo Getting File 
[[ -f ./$1 ]] || rm $1
wget $PULL_URL/$1

echo -e "\n pushing file "
adb root 
adb shell mount -o remount,rw,discard /vendor
adb push $1 /vendor/etc
echo -e "sha1sum: $(adb shell sha1sum /vendor/etc/$1 | cut -d' ' -f1)"
adb shell mount -o remount,ro /vendor
sleep 1
adb shell reboot

echo -e "done..."