#! /usr/bin/env bash

while true; do
read -rsn1 input
if [ "$input" = "q" ]; then
    exit 
fi
sleep 0.1
done & 

alias left="tput cub"
alias right="tput cuf" 
alias down="tput cud"
alias up="tput cup"

order() {
    sleep $1
}

render_border() {
    # order 0.0
    # define vert and horz border symbols
    VERT="|"
    HORZ_ALT="-"
    HORZ="-"
    COLS=$(tput cols)
    LINES=$(tput lines)

    clear; tput sc 

    #cycle 1 for printing top line
    echo -n $VERT
    for ((x=0; x < $(( $COLS - 2 )); x++)); do
        echo -n $HORZ_ALT 
    done
    echo -n $VERT

    #middle cycle
    for ((y=0; y < $(( $LINES - 2 )); y++ )); do
        echo -n $VERT
        for ((x=0; x < $(( $COLS - 2 )); x++)); do
            echo -n " "
        done
        echo -n $VERT
    done

    #end cycle for printing bottom
    echo -n $VERT
    for ((x=0; x < $(( $COLS - 2 )); x++)); do
        echo -n $HORZ 
    done
    echo -n $VERT
    
}

render_dummy() {
    order 0.2
    tput cup 0 0 
    tput cud $((($(tput lines) /2 ) -1 ))
    MSG="welcome to Zui"
    DIFF=${#MSG}
    tput cuf $(( ($(tput cols) - $DIFF -1) /2 ))
    echo -n $MSG
}

version() {
    # order 0.4
    BOLD=$(tput bold)
    RESET=$(tput sgr0)
    VERSION="V0.2.1"
    tput cup $(($LINES -1))
    tput cuf $(($COLS - ${#VERSION}))
    echo -n "$BOLD$VERSION$RESET"
}

render_border 
version 
render_dummy &  
sleep 5
clear