#! /usr/bin/env bash

alias left="tput cub"
alias right="tput cuf" 
alias down="tput cud"
alias up="tput cup"

render_border() {
    # define vert and horz border symbols
    VERT="|"
    HORZ="_"
    COLS=$(tput cols)
    LINES=$(tput lines)

    clear; tput sc 

    #cycle 1 for printing top line
    for ((x=0; x < $COLS; x++)); do
        echo -n $HORZ 
    done

    #end cycle for printing bottom
    for ((x=0; x < $COLS; x++)); do
        echo -n $HORZ 
    done
    
}

render_border