#! /usr/bin/env bash

## Ascii-draw 
## min utility to draw text in ascii made for zclock
## similar to figlet 

# vars
PWD=$(readlink -f "$0")
DIR=$(dirname "$PWD")
FONT="blocks"


## load font 
source $DIR/font/$FONT