#! /usr/bin/env bash

## zclock
## minimal terminal clock

cleanup() {
  tput cnorm 
  clear
}
err() {
  echo "An Error Ocuured And The Program Exited !!"
}

trap cleanup EXIT 
trap err INT 
tput civis

vcenter() {
  for ((x=0; x < $(( $(tput lines) /2 -1 )); x++)); do
    echo 
  done
}

render_time() { 
  TEMP_TIME=$(date +%r)
  while [[ ! $TEMP_TIME == $(date +%r) ]]; do
    sleep 0.1
  done
  for ((x=0; x < $(( ( $(tput cols) -11) /2 )); x++)); do
    echo -ne " "
  done
  while :; do
    TIME=$(date +%r)
    echo -ne "$TIME"
    echo -ne "$(tput cub ${#TIME} )"
    sleep 1
  done
}

clear
vcenter
render_time