#! /usr/bin/env bash

#                   ______     ___           __ __
#                  / ____/__  / (_)  __     / //_/_  ____  ______
#                 / /_  / _ \/ / / |/_/    / ,< / / / / / / / __ \
#                / __/ /  __/ / />  <     / /| / /_/ / /_/ / / / /
#               /_/    \___/_/_/_/|_|____/_/ |_\__, /\__,_/_/ /_/
#                                  /_____/    /____/

# help and more content here 
# ...

# vars
BASE_DIR=$(pwd)
EXT_DIR=$BASE_DIR/ext
BIN_DIR=$BASE_DIR/bin

# put extensions here
EXT_ENABLED=(
    "test_module"
)

# module checking 


# check to make sure the module exists
for EXT in $EXT_ENABLED; do
    if ! [[ -f $EXT_DIR/${EXT} ]]; then 
        echo "$EXT is not availiable in ext directory"
        exit
    fi
done


# check is supplied one is present
EXT_PRESENT=0
for EXT in $EXT_ENABLED; do
    if [[ $EXT == $0 ]]; then
        $EXT_PRESENT=1
    fi
done
    if [[ $EXT_PRESENT != 1 ]]; then
    echo "specified ext is either not enabled or not present"
    exit
fi