#! /usr/bin/env bash

#         _____   ____     __       __
#        /__  /  / __/__  / /______/ /_
#          / /  / /_/ _ \/ __/ ___/ __ \
#         / /__/ __/  __/ /_/ /__/ / / /
#        /____/_/  \___/\__/\___/_/ /_/
# 
# a simple fetch utility 
# i started learning bash so, 
# i thought make smth like this will help me practice

# ! fix the less line problem in logo() and inside module printing
# ! also test to see what happens when modules number exceed logo lines
# TODO add fallback for OS 
# TODO make the plugin mgt flexible
# TODO add os support to "packages" `using case ?`
# TODO add more modules
# TODO add more logo after finishing main part

BASE_DIR=$(dirname "$(readlink -f "$0")")
MODULES_DIR=$BASE_DIR/modules
OS=$(lsb_release -si)
FLAG_DIR=$BASE_DIR/os
source $FLAG_DIR/$OS 

MODULES_ENABLED=(
    ""
    "context"
    "sep"
    ""
    "_os"
    "kernel"
    "_uptime"
    "packages"
    "shell"
)

for MODULE in ${MODULES_ENABLED[@]}; do
    if [[ ! -f $MODULES_DIR/$MODULE ]]; then
        echo "enabled modules is not availiable..."
        exit 1
    fi
    source $MODULES_DIR/$MODULE
done


MAX_LEN=15
if (( $MAX_LEN < ${#MODULES_ENABLED[@]} )); then
    MAX_LEN=${#MODULES_ENABLED[@]}
fi

TEMP=$(( ${#MODULES_ENABLED[@]} + 1 ))

echo 
for ((LOC=1; LOC < $MAX_LEN; LOC++)); do
    flag $LOC
    if (( $LOC < $TEMP )); then
        ${MODULES_ENABLED[$LOC]}
    fi
    echo ""
done