#! /usr/bin/env bash

#         _____   ____     __       __
#        /__  /  / __/__  / /______/ /_
#          / /  / /_/ _ \/ __/ ___/ __ \
#         / /__/ __/  __/ /_/ /__/ / / /
#        /____/_/  \___/\__/\___/_/ /_/
# visit: 


BASE_DIR=$(dirname $0)
echo $BASE_DIR
MODULES_DIR=$BASE_DIR/modules

MODULES_ENABLED=(
    "context"
)

for MODULE in $MODULES_ENABLED; do
    if [[ ! -f $MODULES_DIR/$MODULE ]]; then
        echo "enabled modules is not availiable..."
        exit 1
    fi
    source $MODULES_DIR/$MODULE
done

context