#! /usr/bin/env bash

#         _____   ____     __       __
#        /__  /  / __/__  / /______/ /_
#          / /  / /_/ _ \/ __/ ___/ __ \
#         / /__/ __/  __/ /_/ /__/ / / /
#        /____/_/  \___/\__/\___/_/ /_/
# visit: 


BASE_DIR=$(dirname $0)
echo $BASE_DIR
MODULES_DIR=$BASE_DIR/modules
OS=$(lsb_release -si)
FLAG_DIR=$BASE_DIR/os

MODULES_ENABLED=(
    "context"
    "sep"
)

for MODULE in $MODULES_ENABLED; do
    if [[ ! -f $MODULES_DIR/$MODULE ]]; then
        echo "enabled modules is not availiable..."
        exit 1
    fi
    source $MODULES_DIR/$MODULE
done


MAX_LEN=15
if (( $MAX_LEN < ${#MODULES_ENABLED[@]} )); then
    MAX_LEN=${#MODULES_ENABLED[@]}
fi

source $FLAG_DIR/$OS 
TEMP=$(( ${#MODULES_ENABLED[@]} + 1 ))
echo $TEMP
for ((LOC=1; LOC < $MAX_LEN; LOC++)); do
    flag $LOC
    if (( $LOC < $TEMP )); then
        # $MODULES_ENABLED[$LOC]
        ${MODULES_ENABLED[$LOC]}
        # echo ${MODULES_ENABLED[@]}
    fi
    echo ""
done