#!/usr/env/env bash


# polybar 
THEME=nord-base
polybar-msg cmd quit #kill polybar if running
# killall -q polybar # another way to kill polybar
echo "---" | tee -a /tmp/polybar_nord.log
polybar -c ~/.config/polybar/nord-base/config.ini main 2>&1 | tee -a /tmp/polybar_nord.log & disown



