#! /usr/bin/env bash

#                   ______     ___           __ __
#                  / ____/__  / (_)  __     / //_/_  ____  ______
#                 / /_  / _ \/ / / |/_/    / ,< / / / / / / / __ \
#                / __/ /  __/ / />  <     / /| / /_/ / /_/ / / / /
#               /_/    \___/_/_/_/|_|____/_/ |_\__, /\__,_/_/ /_/
#                                  /_____/    /____/

#* Advanced Manager
# Utility To Handle All Your Scattered Snippets
# here everything is defined in func/your_module
# this is just the base script 

# TODO 
#   - remove all hardcoded paths 
#   - add help msg

# define env vars
BASE_DIR=$HOME/.am

# am func task value sub-value bakup-value

if [[ ! $1 ]]; then
    # help
    exit 1
fi

files=$(ls $BASE_DIR/func)
for file in "${files[@]}"; do
    echo $file
done